### ISSUE TITLE
python 2 support

### ISSUE THREAD

**Issue by schriftgestalt** [robotools/vanilla#102]
Is Python 2 still supported or was it dropped at some point?

In python 2 there is an import error:
```
  File "__init__.py", line 1, in <module>
    from vanilla.vanillaBase import VanillaBaseObject, VanillaBaseControl, VanillaError
  File "vanillaBase.py", line 4, in <module>
    from AppKit import NSFont, NSRegularControlSize, NSSmallControlSize, NSMiniControlSize, \
ImportError: cannot import name NSLayoutAttributeLastBaseline
```

**Comment by justvanrossum** [comment]
It may rather be an accidental dependency on a newer PyObjC.

That said, although we haven't talked about vanilla and Python 2 explicitly, I don't expect Python 2 support for much longer.

**Comment by schriftgestalt** [comment]
I’ll try to fix this then. 
And can you make a ‘python2’ branch just before you decide to drop support for it?

**Comment by benkiel** [comment]
@schriftgestalt Of course, we've been tagging things and can make branches. #101 is there to discuss dropping support for Py2 in vanilla, that has not been done, as @justvanrossum said above.

**Comment by schriftgestalt** [comment]
I just saw that other issue. Thanks. Just send a pull request.

**Comment by takaakifuji** [comment]
@schriftgestalt I just realized that the Install Modules button in Glyphs 2 installs the Py3 only version of vanilla (which has landed to master), and now it seems broken. Maybe you want to pin the version to the commit 092b748. Just in case.

**Comment by schriftgestalt** [comment]
I have fixed that for the cutting edge version already.
