### ISSUE TITLE
Remove (presumably outdated) documentation?

### ISSUE THREAD

**Issue by frankrolf** [robotools/vanilla#111]
I noticed there are two different documentation sites available:

http://vanilla.robotools.dev/en/latest/
https://ts-vanilla.readthedocs.io/en/latest/

I think the 2nd one is outdated, and should perhaps be removed?
Thanks!

**Comment by typemytype** [comment]
that is the plan!!!

http://vanilla.robotools.dev/en/latest/ is the most current one!
