### ISSUE TITLE
Popover can't contain a PopUpButton 

### ISSUE THREAD

**Issue by peternowell** [robotools/vanilla#116]
I have a basic Vanilla list that displays a popover after double-clicking on a list item. I need that popover to include a "dropdown"/PopUpButton, but as soon as I set a callback for that PopUpButton it stops working. The PopUpButton looks normal, but after clicking on it all of the options in the list become disabled and I can’t choose any of them.

I tried this with a Sheet instead of a popover and it works just fine. Is this a bug where Popover can’t include a PopUpButton?

```PYTHON
from vanilla import *

class PopoverWithPopUpButton :

    def __init__(self):
        self.w = Window( (120, 120) )
        self.w.list = List((0, 0, -0, -0), ['A', 'B', 'C'], doubleClickCallback=self.showPopover )
        self.w.open()

    def showPopover(self, sender):
        selection = sender.getSelection()
        if not selection:
            return
        index = sender.getSelection()[0]
        relativeRect = sender.getNSTableView().rectOfRow_(index)
        
        pop = Popover((140, 80), behavior = 'transient')
        pop.popUpButton = PopUpButton((10, 10, -10, 20),
                              ["A", "B", "C"],
                              callback=self.popUpButtonCallback)
        
        pop.open(parentView=sender, preferredEdge='right', relativeRect=relativeRect)

    def popUpButtonCallback(self, sender):
        print("pop up button selection:", sender.get())

PopoverWithPopUpButton()
```

**Comment by justvanrossum** [comment]
You need to keep a reference to the Popover around. If you change `pop = Popover(...)` to `self.pop = Popover(...)` it works.

**Comment by peternowell** [comment]
Thanks Just—that worked! It might make sense to update the popover example in the Vanilla docs to use `self.pop =` instead of just `pop =`, for all those people like me who aren’t experts. Thanks!

**Comment by justvanrossum** [comment]
Yes, or perhaps it's a bug. Let's keep this issue open either way.
