### ISSUE TITLE
[proposal] add ColorCell, EditStepper etc to vanilla

### ISSUE THREAD

**Issue by gferreira** [robotools/vanilla#118]
RoboFont includes several custom UI items which could be useful in other apps.
  
can we move them to vanilla?

| UI item | example |
| --- | --- | 
| `ColorCell` | ![](https://user-images.githubusercontent.com/62717/76617084-3dd70e00-6504-11ea-9b8c-7a4ed0c32630.png) |
| `EditStepper` | ![EditStepper](https://user-images.githubusercontent.com/62717/76617228-a0300e80-6504-11ea-9fdb-1e10ecd2d09c.png) |
| `EditIntStepper` | ![EditIntStepper](https://user-images.githubusercontent.com/62717/76617226-9f977800-6504-11ea-8ce4-0c9c2cd18028.png) |
| `SliderEditStepper` | ![SliderEditStepper](https://user-images.githubusercontent.com/62717/76617224-9e664b00-6504-11ea-9de4-b981b08bd788.png)  |
| `SliderEditIntStepper` | ![SliderEditIntStepper](https://user-images.githubusercontent.com/62717/76617218-9c9c8780-6504-11ea-8d9f-01111ef860f9.png)  |

thanks!

**Comment by gferreira** [comment]
see also #68

**Comment by typesupply** [comment]
Most of these have been added to ezui. I'll look into the ComboListCell for List2 on issue #68.
