### ISSUE TITLE
Auto Layout Window floats away when resized

### ISSUE THREAD

**Issue by colinmford** [robotools/vanilla#119]
Hey all,

I was trying out Auto Layout (seems really cool!) but when the vertical direction is specified, resizing the window also causes the window to move upwards.

For instance, using the demo code on https://github.com/robotools/vanilla/blob/master/Documentation/source/concepts/positioning.rst:

```python
w = vanilla.Window((200, 200), minSize=(100, 100))
w.button = vanilla.Button("auto", "Hello")
rules = [
    # Horizontal
    "H:|-[button]-|",
    # Vertical
    "V:|-[button]-|"
]
metrics = {}
w.addAutoPosSizeRules(rules, metrics)
w.open()
```

Results in this (gif):
![Untitled 480](https://user-images.githubusercontent.com/671409/81221847-5e29c300-8fb1-11ea-9a60-ab765b328028.gif)

It floats upwards when the mouse is moved while clicking and holding to resize the window.

It doesn't do this when the horizontal direction is the only one specified (i.e. if you comment out ` "V:|-[button]-|"`, or use different rules).

I assume something like a width variable is mistakenly put in the "y" coordinate spot or something, but I don't know enough about how Auto Layout works yet to go hunting for it.

(RoboFont Version 3.4b (build 2004181428), macOS 10.15.4)

**Comment by typemytype** [comment]
on 10.13 it shifts just a tiny little bit... 

I would like to blame the os.. 

cc @typesupply

**Comment by colinmford** [comment]
Update: it seems like it has to do with the difference between the computed size of the window, vs what the minimum size for the window is. 

If you replace the first line with `w = vanilla.Window((200, 200), minSize=(100, 200))`, it floats up twice as fast, if you replace it with `w = vanilla.Window((200, 200), minSize=(100, 50))`, it doesn't float up at all.

**Comment by colinmford** [comment]
@typemytype 
> on 10.13 it shifts just a tiny little bit...

It may also have to do with the resolution, maybe a Retina (5K) screen exaggerates it?

**Comment by typemytype** [comment]
mm, the height of the window is less then 100 when the rules are applied

maybe vanilla has to clip the min max values when using auto layout... 
probably you will see similar issues a `SplitView`

**Comment by typesupply** [comment]
I've seen this in some cases since I made the first experiments and it has baffled me. My current guess is that this is happening when windows are set to resize and they contain element that does not have a default size and is set to size itself relative to the window. I haven't been able to come up with atomic tests to isolate the issue. Though, honestly., I haven't spent a ton of time on it.

**Comment by typemytype** [comment]
I would like to consider this as "not-so-correctly-filled-in-numbers"...

Similar to this the example below. Only when you see real numbers it makes sense. When the auto resize rules are applied the size of the window is smaller then the `minSize`, so that conflicts while resizing that window. 


```python
import vanilla

w = vanilla.Window((200, 200), minSize=(300, 300))
w.open()
```

Maybe a warning if this happens on window.open is nice, so you know.


```python
import vanilla


w = vanilla.Window((200, 200), minSize=(100, 100))
w.button = vanilla.Button("auto", "Hello")
rules = [
    # Horizontal
    "H:|-[button]-|",
    # Vertical
    "V:|-[button]-|"
]
metrics = {}
w.addAutoPosSizeRules(rules, metrics)


###### patch:

from warnings import warn

class VanillaWarning(Warning): pass

def open(self):
    """
    Open the window.
    """
    if self._window is None:
        raise ValueError("can't re-open a window")
        
    if self._initiallyVisible:
        self.show()
    # We retain ourselves to ensure we don't go away, even if our
    # caller doesn't keep a reference. It's balanced by a release
    # in windowWillClose_().
    self.retain()
    
    size = self._window.frame().size
    minSize = self._window.minSize()
    if size.width < minSize.width or size.height < minSize.height:
        warn("The windows `minSize` is bigger then the initial size.", VanillaWarning)
    

open(w)
```

**Comment by typesupply** [comment]
Sounds good to me!

**Comment by colinmford** [comment]
Thanks, All!
