### ISSUE TITLE
Box Auto Layout not working

### ISSUE THREAD

**Issue by colinmford** [robotools/vanilla#120]
Hi there,

I am having trouble getting Box to work with Auto Layout.

Given the "Box" sample code:
```python
from vanilla import Window, Box, TextBox
class BoxDemo:
    def __init__(self):
        self.w = Window((150, 70))
        self.w.box = Box((10, 10, -10, -10))
        self.w.box.text = TextBox((10, 10, -10, -10), "This is a box")
        self.w.open()
BoxDemo()
```
<img width="262" alt="image" src="https://user-images.githubusercontent.com/671409/81862729-1d452780-9538-11ea-9947-8b5b3cb00743.png">

When converted to Auto Layout, it doesn't show correctly:
```python
from vanilla import Window, Box, TextBox
class BoxDemoAutoLayout:
    def __init__(self):
        self.w = Window((150, 70))
        self.w.box = Box("auto")
        self.w.box.text = TextBox((10, 10, -10, -10), "This is a box")
        rules = [
            # Horizontal
            "H:|-border-[box]-border-|",
            # Vertical
            "V:|-border-[box]-border-|"
        ]
        metrics = {
            "border" : 10,
        }
        self.w.addAutoPosSizeRules(rules, metrics)    
        self.w.open()
BoxDemoAutoLayout()
```
<img width="262" alt="image" src="https://user-images.githubusercontent.com/671409/81862734-2209db80-9538-11ea-9326-5a3a6a29f933.png">

Replacing "Box" with "Group" works, so it leads me to believe the issue is in "Box":
```python
from vanilla import Window, Group, TextBox
class BoxDemoAutoLayout:
    def __init__(self):
        self.w = Window((150, 70))
        self.w.box = Group("auto")
        self.w.box.text = TextBox((10, 10, -10, -10), "This is a box")
        rules = [
            # Horizontal
            "H:|-border-[box]-border-|",
            # Vertical
            "V:|-border-[box]-border-|"
        ]
        metrics = {
            "border" : 10,
        }
        self.w.addAutoPosSizeRules(rules, metrics)    
        self.w.open()
BoxDemoAutoLayout()
```
<img width="262" alt="image" src="https://user-images.githubusercontent.com/671409/81866429-300e2b00-953d-11ea-9298-f97e60091937.png">

Looking at the Box code, nothing jumps out at me that inherently would prevent Auto Layout from working, but it seems to be broken.

**Comment by typemytype** [comment]
It does work when the contentView of a Box returns the default from VanillaBaseObject, which is the `_nsObject`, instead of the content view of the box... 

This was an edit 12 years ago... @tal: I dont remember why, and it probably has to change...

**Comment by typemytype** [comment]
I remember... the content view is also used to add other views and this must be the content view of the box... not the box itself

**Comment by typemytype** [comment]
@tal: an option could be to add extra callback in `VanillaBaseObject._getLayoutContentView()` which basically returns the `_getContentView()` but allows `Box` to over write it and return a different "contentView" 

will make a PR

**Comment by typesupply** [comment]
FYI, I'm not <at>tal. 😄

**Comment by typemytype** [comment]
oh that would have been so easy, otherwise!!

**Comment by colinmford** [comment]
Thanks, All!
