### ISSUE TITLE
adding ModalWindow

### ISSUE THREAD

**Issue by typemytype** [robotools/vanilla#126]
dialogKit had a ModalWindow, which is nice to have in some occasions 

this can be added to `vanillaWindow.py` 

```python
from AppKit import NSModalPanelWindowLevel
from vanilla import Window


class ModalWindow(Window):

    nsWindowLevel = NSModalPanelWindowLevel

    def __init__(self, *args, **kwargs):
        kwargs["closable"] = False
        kwargs["miniaturizable"] = False
        self._doCenter = True
        if "center" in kwargs:
            self._doCenter = kwargs["center"]
            del kwargs["center"]

        super(ModalWindow, self).__init__(*args, **kwargs)

    def open(self):
        super(ModalWindow, self).open()
        if self._doCenter:
            self.center()
        NSApp().runModalForWindow_(self._window)

    def windowWillClose_(self, notification):
        super(ModalWindow, self).windowWillClose_(notification)
        NSApp().stopModal()
```

**Comment by colinmford** [comment]
Yeah, I think this will be pretty useful!

**Comment by justvanrossum** [comment]
Note that in general, modal windows are considered very poor UI design.

**Comment by typemytype** [comment]
True... its to have alternative for the archived [dialogKit.ModalDialog](https://github.com/typesupply/dialogKit/blob/master/Lib/dialogKit/_dkVanilla.py#L44).

sheet are also modal and there are cases where a modal window is a nice option.

**Comment by justvanrossum** [comment]
A sheets is only modal relative to its parent window.

A modal window is only "a nice option" if the code really can't be changed to support a non-modal UI.

A ModalDialog has no place in a modern application — that's probably why it was archived.

**Comment by typemytype** [comment]
dialogKit is archived in favour of vanilla, to old to much FL code in there

**Comment by justvanrossum** [comment]
Ah of course, I forgot.

**Comment by gferreira** [comment]
[Pop Up Tools](https://github.com/typesupply/popuptools) is very nice, and uses a modal window…

**Comment by justvanrossum** [comment]
> Pop Up Tools is very nice, and uses a modal window…

That's not a modal window at all, it's like a contextual menu. If you click somewhere else it disappears. It doesn't block you from doing somthing else.

**Comment by gferreira** [comment]
@justvanrossum I think the idea is that it doesn’t disappear… see [Make the window better](https://github.com/typesupply/popuptools/issues/2)

**Comment by typemytype** [comment]
An frequent used example of a modal dialog is an Open panel.
see https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/dialogs/

I indicates a higher level of user attention: "the app cannot do anything until you give it a file to open..." 

Its a convenient window class, and annoying to make it each time you needs it.

**Comment by justvanrossum** [comment]
I read that as "don't disappear if a click occurs inside the window, but outside of a control".

**Comment by justvanrossum** [comment]
On macOS 10.15 not even the actual Open panel is modal... (On 10.10 it is, I don't know when it changed.)

Modal windows/dialogs are a remnant of '80s & '90s UI design and should be avoided at all cost.

**Comment by justvanrossum** [comment]
"App-modal" I should say. There's obviously use for document-modal or window-modal windows, but those are "sheets" and we already have them.

**Comment by gferreira** [comment]
there are valid use cases for modal dialogs, see [Modal & Nonmodal Dialogs: When (& When Not) to Use Them](https://www.nngroup.com/articles/modal-nonmodal-dialog/)

> Modal dialogs interrupt users and demand an action. They are appropriate when user’s attention needs to be directed toward important information.

the most reasonable course of action here seems to be:

- make modal window available for convenience, so that developers don’t have to write their own every time they need it
- add a warning to the docs saying that they should be avoided at all cost

**Comment by typesupply** [comment]
I was reading the latest release notes and noticed that [sheets look like modal windows in macOS 11](https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/#sheets).

**Comment by typesupply** [comment]
I added the version that I created for ezui that was, in turn, based on the one in RoboFont.

```python
import vanilla

class Test:

    def __init__(self):
        self.w = vanilla.ModalWindow((200, 200))
        self.w.b = vanilla.Button((10, 10, -10, 20), "Close", callback=self.closeCallback)
        self.w.open()

    def closeCallback(self, sender):
        self.w.close()

Test()
```
