### ISSUE TITLE
relativeRect bug: Popovers don't open for list items at the bottom of a list

### ISSUE THREAD

**Issue by peternowell** [robotools/vanilla#128]
This is a bizarre bug, and I've been able to reproduce it in multiple Vanilla lists that open popovers with a relativeRect. Even the demo in the docs (just add another several items to the list)! Popovers open just fine for most list items, but popovers fail to open for items near the bottom of the list. I've been troubleshooting this for the past couple hours, and analyzing the relativeRect data... I can't see any errors, nor a consistent pattern for precisely when the popovers stop opening. For what it's worth, I don't think this was a problem in some older versions of Vanilla... I just updated for the first time in several months (at least).

```python
from vanilla import Window, List, Popover, TextBox

class PopoverExample:

    def __init__(self):
        self.w = Window((120, 120))
        self.w.list = List((0, 0, -0, -0),
                ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
                selectionCallback=self.showPopoverCallback)
        self.w.open()

    def showPopoverCallback(self, sender):
        selection = sender.getSelection()
        if not selection:
            return
        index = sender.getSelection()[0]
        relativeRect = sender.getNSTableView().rectOfRow_(index)
        self.pop = Popover((140, 80))
        self.pop.text = TextBox((10, 10, -10, -10), 'This is a popover.')
        self.pop.open(parentView=sender, preferredEdge='right', relativeRect=relativeRect)

PopoverExample()
```

**Comment by justvanrossum** [comment]
It seems to have to do with the `relativeRect`: if the y value is too high (outside of the window or parentview) the popover doesn't show. Whether this is OS behavior or vanilla behavior I do no know off hand.

**Comment by form-follows-function** [comment]
@peternowell @justvanrossum I've recently got aware of that bug as well. I somehow got around it by adding more UI components. Maybe it's specifally related to the NSTextBox (which shouldn't be a problem from stating the code, as far as I can tell).

**Comment by form-follows-function** [comment]
@justvanrossum @peternowell I've recently encountered this bug. It can be fixed by adressing the sender's _nsObject, replacing 
`self.pop.open(parentView=sender, …` with`self.pop.open(parentView=sender.getNSTableView(), …`

**Comment by peternowell** [comment]
@form-follows-function 🙏  After briefly testing this solution, it seems to work. In fact, it works better than before because now popovers will move up and down as I scroll the list—to remain next to their list item. Yes!

**Comment by form-follows-function** [comment]
This issue can be closed
