### ISSUE TITLE
Invalid condition

### ISSUE THREAD

**Issue by schriftgestalt** [robotools/vanilla#131]
https://github.com/robotools/vanilla/blob/379a08d3329f5178f9a47bd8770de202d348a529/Lib/vanilla/vanillaBase.py#L94

Does this make sense?

**Comment by justvanrossum** [comment]
I think it should be `if w <= 0 and l >= 0:`.

Similar for the `NSViewHeightSizable` condition.

I'm not sure where that `w > 0` is coming from, but it doesn't make sense to me, either.
