### ISSUE TITLE
revamping vanilla dialogs 

### ISSUE THREAD

**Issue by typemytype** [robotools/vanilla#136]
for now only `askYesNo` and `askYesNoCancel` are available

https://github.com/robotools/vanilla/blob/master/Lib/vanilla/dialogs.py

**Comment by typemytype** [comment]
Im in favour of adding `def ask(...)` which is the most generic method `askYesNo` is a bit more specific. 

```python
ask(
    "message",
    "info",
    altertStyle="critical",
    buttons=[dict(title="Yes", callback=yesCallback), dict("Nooooooooooo", callback=nooooooooCallback) ]
)
```

also add:

* [accessoryView](https://developer.apple.com/documentation/appkit/nsalert/1530575-accessoryview?language=objc)
* [icon](https://developer.apple.com/documentation/appkit/nsalert/1531688-icon?language=objc)
* [showsHelp](https://developer.apple.com/documentation/appkit/nsalert/1535856-showshelp?language=objc)
* use string identifiers for alert styles: 
    * `informational`
    *  `critical` 
    * `warning


both the alert style as the button titles should be backward compatible

**Comment by benkiel** [comment]
Yes, love this.

**Comment by typesupply** [comment]
A couple of things on ask:

1. Should the displayed buttons follow the order of the items in the button title list?

If my button titles are:

```python
buttonTitles=[
    dict(title="A", returnCode=1),
    dict(title="B", returnCode=2),
    dict(title="C", returnCode=3),
    dict(title="D", returnCode=3),
    dict(title="E", returnCode=5)
],
```

They will be shown to the user as [E D C B A]. Maybe it's logical? It confused me at first.

2. I'd like to be able to control the default button and add a key command.

- `default` : True | False (False is the default)
- `keyCommand` : Same structure as [Button.bind](https://vanilla.robotools.dev/en/latest/objects/Button.html#vanilla.Button.bind)

These are discussed in the `addButtonWithTitle` [documentation](https://developer.apple.com/documentation/appkit/nsalert/1524532-addbuttonwithtitle?language=objc).

I can write this code. I just want to make sure it's an okay idea.

**Comment by typemytype** [comment]
1) The order is keept as it was before this changes, which is indeed reversed. 

2) The Default button is just the first one... 
when a button has "Cancel" as title it will have a key equivalent of esc, same for "Don't Save" with cmd-D
see https://developer.apple.com/documentation/appkit/nsalert/1532992-buttons?language=objc



having an optional "default" and "keyCommand" would be super useful! 

`addButtonWithTitle` returns the NSButton object which can be used to change the its behaviour

I already added "callback" as option, which is called when the button is hit

**Comment by typesupply** [comment]
Can we close this?

**Comment by benkiel** [comment]
Yes.
