### ISSUE TITLE
Request: unified way to add tooltips

### ISSUE THREAD

**Issue by mekkablue** [robotools/vanilla#142]
Right now, I need to access the NS object and call its `setToolTip:` function. The problem is that the object getter is syntactically different for each vanilla object:

```python
self.w.myTextField.getNSTextField().setToolTip_("Tooltip text.")
self.w.myPopupButton.getNSPopUpButton().setToolTip_("Tooltip text.")
```

How about something like this instead:

```python
self.w.myTextField.tooltip("Tooltip text.")
self.w.myPopupButton.tooltip("Tooltip text.")
```

Or am I overthinking the issue?

**Comment by justvanrossum** [comment]
Yes, but: `self.myTextField.setToolTip("...")`.

Both `NSView` and `NSControl` support the `setToolTip_` method, so adding `setToolTip` to `VanillaBaseObject` would cover a lot of cases.

Would you like to make a PR?

**Comment by RafalBuchner** [comment]
hi Just :) , just added PR. I hope it looks ok

**Comment by typesupply** [comment]
Thanks @RafalBuchner!

```python
import vanilla

w = vanilla.Window((200, 40))
w.b = vanilla.Button((10, 10, -10, 20), "Hover Over Me")
w.b.setToolTip("Thanks @RafalBuchner :)")
w.open()
```
