### ISSUE TITLE
Make a ColorWellList2Cell that looks like it is supposed to.

### ISSUE THREAD

**Issue by typesupply** [robotools/vanilla#146]
This looks stupid:

<img width="221" alt="image" src="https://user-images.githubusercontent.com/4992934/126713273-31e4be1a-a2c2-464b-8763-fab77f4886e9.png">

[Setting setBordered on the NSColorWell makes it uneditable.](https://developer.apple.com/documentation/appkit/nscolorwell/1528015-bordered?language=objc) So, this thing will have to be built from scratch. @typemytype you don't happen to have anything that can be used for this, do you?

**Comment by typemytype** [comment]
you mean these cells: 

<img width="94" alt="image" src="https://user-images.githubusercontent.com/1190358/126838568-3dfce896-5e67-495c-82a0-b62e248a2bba.png">

I can donate them to vanilla

**Comment by typesupply** [comment]
Apple fixed this.
