### ISSUE TITLE
Problem with NSRightTextAlignment (and NSCenterTextAlignment)

### ISSUE THREAD

**Issue by schriftgestalt** [robotools/vanilla#156]
Apple seems to have switch the values of those two constants in macOS12 and pyobjc is not correctly handling that. I reported it there: https://github.com/ronaldoussoren/pyobjc/issues/401

The easiest would be to switch to the newer API and use `NSTextAlignmentRight` (and `NSTextAlignmentCenter`). Those seem to work fine.

**Comment by justvanrossum** [comment]
Thanks. A pr would be fantastic.

**Comment by schriftgestalt** [comment]
I can do that but wasn't sure if it is save to just replace all occurrences. Clients should not directly use them, but if they do, it may break (I would not import both).

**Comment by typemytype** [comment]
it seems like both are available from 10.0+ so this removing the deprecated alignments should not break much

https://developer.apple.com/documentation/uikit/nstextalignment?language=objc
