### ISSUE TITLE
Add support for new Yosemite views, controls, etc.

### ISSUE THREAD

**Issue by typesupply** [robotools/vanilla#17]
AppKit Release notes: https://developer.apple.com/library/mac/releasenotes/AppKit/RN-AppKit/
# ~~NSVisualEffectView~~ (done)

This is handled simply with a new Group kwarg:

``` python
self.w.group = vanilla.Group((10, 10, -10, -10), blendingMode="withinWindow")
```

Internally, this is handled not so simply.
# ~~Window Styles~~ (done)

These are the current init kwargs that specify window appearance.

``` python
closable = True | False
miniaturizable = True | False
initiallyVisible = True | False
fullScreenMode = None | "primary" | "auxillary"
```

10.10 adds new appearance options: https://developer.apple.com/library/mac/releasenotes/AppKit/RN-AppKit/#10_10Window
### Full Size Content View

This pushes the content view underneath the title and toolbars. Those should then be set to be transparent. (Not always, but I don't want two flags so if the transparency is not desired a coder can override this with `getNSWindow().setTitlebarAppearsTransparent_(False)`.) I'm not sure when this is used but we may as well make it possible.

``` python
self.w = vanilla.Window(..., fullSizeContentView=False, ...)
```

``` python
try:
    NSFullSizeContentViewWindowMask
except NameError:
    NSFullSizeContentViewWindowMask = 1 << 15
```

``` python

if fullSizeContentView and osVersion >= "10.10":
    mask = mask | NSFullSizeContentViewWindowMask

# ... later ...

if fullSizeContentView and osVersion >= "10.10":
    self._window.setTitlebarAppearsTransparent_(True)
```
### Titlebar Visibility

This will show/hide the title of the window. If it is hidden, the toolbar moves to the space formally occupied by the title.

``` python
self.w = vanilla.Window(..., titleVisible=True, ...)
```

``` python
try:
    NSWindowTitleVisible
except NameError:
    NSWindowTitleVisible  = 0
    NSWindowTitleHidden = 1
```

``` python
if osVersion >= "10.10":
    if not titleVisible:
        self._window.setTitleVisibility_(NSWindowTitleHidden)
    else:
        self._window.setTitleVisibility_(NSWindowTitleVisible)
```
### NSTitlebarAccessoryViewController

This is an advanced thing that should be handled outside of vanilla.
# ~~HUDWindow~~ (done)
# Action Button with Menu

How would callbacks work?
# List
- more cell types
  - ~~add ticks to list slider~~ (done)
  - ~~image cell~~ (done)
  - ~~segmented cell~~ (done)
- demos
  - ~~image cell~~
  - ~~checkbox cell~~
  - ~~slider cell~~
  - ~~popup cell~~
- ~~column width bug~~ (hopefully done)
- ~~should the column resizing behavior be an **init** kwarg?~~ (no. this is handled with column construction data.)
- ~~make it possible to disable column sorting.~~ (done)
- is dataSource needed? It adds lots of complexity to the code.
- more documentation about and examples of drag and drop.
### Cell vs. View Mode

Here's a tricky one: the use of cells in NSTableView is now deprecated. Instead, we are supposed to use views. That's easy enough to switch **but** mixing cells and views in the same table is not permitted. So, we can't simply change things like SliderListCell to be view based instead of cell based. We do need to make the change though. (Plus, view based tables can do some really useful stuff.)

I think we could handle this change by automatically detecting the cell types during `__init__` by skimming the "cell" settings in columnDescriptions. If anything there is cell based, the table view would be set to cell mode. Otherwise it would be set to view mode.

I'm still researching this so this could change.
# Localization

This is going to require some research on how localization is handled at the app level. I'm not sure if localization will be able to be specified on the fly per control, which is what would be ideal for vanilla.
# Auto-Layout

This is going to be tricky but it might be a very worthwhile thing to add.
# NSMatrix

This class is now deprecated. It looks like RadioGroup can be rebuilt with a Group as a parent and individual buttons set to be radio buttons. According to the documentation, those will automatically be linked as a group in 10.8+.
# Misc
- ~~Remove any hacks needed for < 10.6.~~ (done)
- ~~conditionally remove cell interaction when osVersion >= 10.10 since cells are slowly being deprecated.~~ (done. Apple hasn't assigned view based methods for everything yet so there are still some cell calls.)
- add a convenience method for getting the selected item from a popup button

**Comment by schriftgestalt** [comment]
> Column sorting can now be turned off on a full list or single column basis. Example

Are there any plans to move that into that master branch?

**Comment by typesupply** [comment]
I'd love to, but I don't have time right now. My open source time is going to other projects. Patches are welcome!

**Comment by schriftgestalt** [comment]
I had a quick look at the changes. Some are really related to changes in Yosemite. But there are several things that should work in earlier version, too.

Why I can across this is someone tried to write a script that works in RoboFont and Glyphs. And RF 1.7 seems to use a version of vanilla that supports this particular argument (so it might use this branch?).

**Comment by justvanrossum** [comment]
Some of this stuff apparently is integrated now, some is not. I suggest to close this issue and open new ones for the remaining feature requests, if that's indeed what they are.

**Comment by typemytype** [comment]
ActionButton is added see https://github.com/typesupply/vanilla/blob/cf0707e29e489c9e5b5bad165f8fd2256881c9ef/Lib/vanilla/vanillaPopUpButton.py#L121

**Comment by typemytype** [comment]
related to Lists:

* is dataSource needed? It adds lots of complexity to the code.

yes that is needed, only to support searching and shared dateSource over different views

* more documentation about and examples of drag and drop.

will create a new issue for that

**Comment by polarlighthouse** [comment]
Is there any possibility to get the dark VisualEffectViews working?

I can trigger light vibrant windows by adding
`self.w.blend = Group((0, 0, 0, 0), blendingMode='behindWindow')`

Anyways since there is [https://github.com/typesupply/vanilla/blob/2d27b1fe7abfd94a3cc6d574efe804dfad1d4029/Lib/vanilla/vanillaGroup.py#L11](url) we have no option to choose between the VisualEffectViews, not even when _nsObject is triggered, or is there?

**Comment by form-follows-function** [comment]
So, I've got that fixed by adding: 

`        view = self.w

        visualEffectView = NSVisualEffectView.new()
        visualEffectView.setAutoresizingMask_(NSViewWidthSizable|NSViewHeightSizable)
    
        visualEffectView.setWantsLayer_(True)
        visualEffectView.setFrame_(frame)
        visualEffectView.setState_(NSVisualEffectStateActive)
        visualEffectView.setMaterial_(NSVisualEffectMaterialDark)
        visualEffectView.setBlendingMode_(NSVisualEffectBlendingModeBehindWindow)

        self.w._window.contentView().addSubview_positioned_relativeTo_(visualEffectView, NSWindowBelow, self.w)

        self.w._window.setTitlebarAppearsTransparent_(True)
        self.w._window.setStyleMask_(self.w._window.styleMask() | NSFullSizeContentViewWindowMask)
        
        appearance = NSAppearance.appearanceNamed_('NSAppearanceNameVibrantDark')
        self.w._window.setAppearance_(appearance)`

**Comment by form-follows-function** [comment]
> a patch to support embedded Groups into a ScrollView
> 
> https://gist.github.com/typemytype/c9ac5349183209a7d3e7
> 
> I can also implement this and send a pull request...

Been 6 years, but could you pull request this? It would be handy to use ScrollView without relying on pyobjc and keep vanilla interoperatable within itself.

**Comment by schriftgestalt** [comment]
Just started to read the thread again after seeing the notification. I found this:
> Full Size Content View
This pushes the content view underneath the title and toolbars. Those should then be set to be transparent. 

The full size content view and titlebar transparency should not be set together. There are a lot cases that need a visible titlebar. It is used when there is a scroll view adjacent to the toolbar and the scrolled content should go under the (translucent) title bar. See Safari and Maps.

**Comment by form-follows-function** [comment]
@schriftgestalt 
> Just started to read the thread again after seeing the notification. I found this:
> 
> > Full Size Content View
> > This pushes the content view underneath the title and toolbars. Those should then be set to be transparent.
> 
> The full size content view and titlebar transparency should not be set together. There are a lot cases that need a visible titlebar. It is used when there is a scroll view adjacent to the toolbar and the scrolled content should go under the (translucent) title bar. See Safari and Maps.

Totally makes sense to me and agree, however my concerns on `NSFullSizeContentViewWindowMask` and the ScrollView weren't related. Anyways, I think this should be stated in the pull request's documentation or maybe add an additional exception.

**Comment by typemytype** [comment]
@form-follows-function made a new issue for this request --> https://github.com/robotools/vanilla/issues/132
