### ISSUE TITLE
MacOS Ventura and vanilla.Tabs

### ISSUE THREAD

**Issue by HugoJourdan** [robotools/vanilla#172]
vanilla.Tabs are not working correctly on the latest mac OS Ventura.
All tabs except the first one, are bugged. See with this example :

```
from vanilla import Window, Tabs, TextBox, Button

class TabsDemo:

    def __init__(self):
        self.w = Window((250, 200))
        self.w.tabs = Tabs((10, 10, -10, -10), ["Tab One", "Tab Two"])
        tab1 = self.w.tabs[0]
        tab1.button = Button((50, 40, -50, 20), "A Button")
        tab1.text = TextBox((10, 10, -10, -10), "This is tab 1")
        tab2 = self.w.tabs[1]
        tab2.button = Button((50, 40, -50, 20), "A Button")
        tab2.text = TextBox((10, 10, -10, -10), "This is tab 2")
        self.w.open()

TabsDemo().
```

**Comment by typesupply** [comment]
I can confirm this and will work on it. **Thanks for the great test case!**

For my own reference when I pick this up: switch to a [NSTabViewController](https://developer.apple.com/documentation/appkit/nstabviewcontroller?language=objc) model.

**Comment by typesupply** [comment]
This should be closed now. Thanks @HugoJourdan!

**Comment by HugoJourdan** [comment]
It seems to not be fixed.
I forgot to mention that it happened when opening UI with :

```python
if __name__ == "__main__":
    from vanilla.test.testTools import executeVanillaTest
    executeVanillaTest(TabsDemo)
```

Here is full code : 

```python
from vanilla import Window, Tabs, TextBox, Button

class TabsDemo:

    def __init__(self):
        self.w = Window((250, 200))
        self.w.tabs = Tabs((10, 10, -10, -10), ["Tab One", "Tab Two"])
        tab1 = self.w.tabs[0]
        tab1.button = Button((50, 40, -50, 20), "A Button")
        tab1.text = TextBox((10, 10, -10, -10), "This is tab 1")
        tab2 = self.w.tabs[1]
        tab2.button = Button((50, 40, -50, 20), "A Button")
        tab2.text = TextBox((10, 10, -10, -10), "This is tab 2")
        self.w.open()


if __name__ == "__main__":
    from vanilla.test.testTools import executeVanillaTest
    executeVanillaTest(TabsDemo)
```

**Comment by typemytype** [comment]
what is your OS? I cannot reproduce this on ventura

**Comment by HugoJourdan** [comment]
Mac OS Ventura 13.1 (22C65)

**Comment by HugoJourdan** [comment]
I tried to update to last Ventura version 13.2.1 (22D68).
But the issue persists.

![Screenshot 2023-02-24 at 17 58 01](https://user-images.githubusercontent.com/76793951/221240694-3dc7b2e0-1853-4eb3-9628-a34f8923e10f.png)

**Comment by typemytype** [comment]
that change is not yet available on the pip version.. there has not been a release since 

try with `pip install git+https://github.com/robotools/vanilla`  to get the latest from the main branch

**Comment by HugoJourdan** [comment]
Oh ! I didn't notice it.
It's fixed, thanks.

**Comment by HugoJourdan** [comment]
I'm back with another issue related to this one.
The same problem happen when I use a tab inside another tab.
First tab work as expected but the others are glitched.

**Comment by schriftgestalt** [comment]
I just updated the vanilla that ships for Glyphs and now I get problems with TabViews. I narrowed it down to 1498332 . 

- https://forum.glyphsapp.com/t/italic-extremes-plugin-broken/28553 
- https://github.com/Nagwa-Limited-Community/Glyphs-MATH-Plugin/issues/22

I suspect this line: https://github.com/robotools/vanilla/blob/0881768372fdf774210b2111b381e8ce240c8274/Lib/vanilla/vanillaTabs.py#L53
