### ISSUE TITLE
All window bindings call hasattr.

### ISSUE THREAD

**Issue by typesupply** [robotools/vanilla#178]
All window bindings (most significantly resize and move) call the [_alertBindings method](https://github.com/robotools/vanilla/blob/master/Lib/vanilla/vanillaWindows.py#L595). This method makes extensive use of `hasattr` and `Window` is a subclass of `NSObject`. In the past, `hasattr` has been a major performance issue for PyObjC when used in code that is called frequently. During move and resize, this will be called **very** frequently.

We should figure out a way to eliminate the `hasattr` use. The `_alertBindings` method has notes about why `hasattr` is used, but looking at it many years later, I wonder if the solution may be to simply [establish the bindings dict](https://github.com/robotools/vanilla/blob/master/Lib/vanilla/vanillaWindows.py#L166) before the window delegate is set.

**Comment by typemytype** [comment]
moving the `_binding` dict to class level should also enable that the attribute is always available
