### ISSUE TITLE
vanillaList2 contextual menu

### ISSUE THREAD

**Issue by typemytype** [robotools/vanilla#192]
not yet implemented but there are two options:

* give a fixed "menu", by `nsTableView.setMenu_(menu)`
* a contextual menu on demand with by subclassing `nsTableView. menuForEvent_(...)`  see https://developer.apple.com/documentation/appkit/nsview/1483231-menuforevent?language=objc

I would opt for the second option as this is more flexible, the menu can change based on fe selection...

@typesupply

**Comment by typesupply** [comment]
It looks like `List` did both:

- `[menuForEvent_](https://github.com/robotools/vanilla/blob/master/Lib/vanilla/vanillaList.py#L36)` and `[_menuForEvent](https://github.com/robotools/vanilla/blob/master/Lib/vanilla/vanillaList.py#L935)`
- `[setMenu](https://github.com/robotools/vanilla/blob/master/Lib/vanilla/vanillaList.py#L1100)`

I probably just didn't copy/paste the old code. It might be usable as is. I'm fine with whatever you want to do.
