### ISSUE TITLE
Widgets inside GridView (sometimes) don't show up

### ISSUE THREAD

**Issue by simoncozens** [robotools/vanilla#201]
This code:

```python
from PyObjCTools import AppHelper

import vanilla

w = vanilla.Window((200,200))
w.textEditor = vanilla.TextEditor((0,0,100,20), "Standalone")
w.gridView = vanilla.GridView(
            (0,30, 200, 200),
            [{"cells": [
                vanilla.TextBox((0,0,-0,-0), "Widget1"),
                vanilla.TextEditor((0,0,100,20), "Widget2"),
                vanilla.TextBox((0,0,-0,-0), "Widget3"),
             ]}],
        )
w.show()

AppHelper.runEventLoop()
```

gives a window like so:

<img width="201" alt="Screenshot 2023-12-21 at 12 42 00" src="https://github.com/robotools/vanilla/assets/106728/1e464ad5-a7b2-4b96-b119-205932d91d74">

Put them inside a group and all is well:

```python
w = vanilla.Window((300, 300))
w.textEditor = vanilla.TextEditor((0,0,100,20), "Standalone")
g = vanilla.Group("auto")
g.widget1 = vanilla.TextBox((0,0,-0,-0), "Widget1")
g.widget2 = vanilla.TextEditor((0,0,100,20), "Widget2")
g.widget3 = vanilla.TextBox((0,0,100,20), "Widget3")
w.gridView = vanilla.GridView(
    (0,30, 200, 200),
    [{"cells": [g.widget1, g.widget2, g.widget3]}],
)

w.open()
```

<img width="301" alt="Screenshot 2023-12-21 at 12 59 00" src="https://github.com/robotools/vanilla/assets/106728/f6baa42d-1ef5-4209-87ae-21f95f9ad05b">

**Comment by simoncozens** [comment]
(In the version of Vanilla in Glyphs.app, the "put them in a group" trick doesn't work either.)

**Comment by typemytype** [comment]
see the example in the vanilla documentation: https://vanilla.robotools.dev/en/latest/objects/GridView.html#module-vanilla

The "trick" is to keep a reference of the vanilla object.
