### ISSUE TITLE
VanillaList - editCallback and sorting by clicking the column's header

### ISSUE THREAD

**Issue by luke-snider** [robotools/vanilla#23]
When sorting a column by clicking the column's header I get a editCallback. This might be on purpose, because the order changes and somehow the list is edited, but at the same time it is not edited because the entries in the list stay the same. Would it be rude to ask for something like a "sortationCallback" in order to be able to not get an "editCallback" when the column's header is clicked by the user? Or is there somehow a way to circumvent the editCallback when the header is clicked?

**Comment by typesupply** [comment]
This is fixed in List2

```python
import vanilla

class Test:

    def __init__(self):
        items = [
            dict(value=i) for i in "cba"
        ]
        self.w = vanilla.Window((200, 200))
        self.w.l = vanilla.List2(
            (0, 0, 0, 0),
            items=items,
            columnDescriptions=[
                dict(
                    identifier="value",
                    title="test",
                    sortable=True
                )
            ],
            editCallback=self.editCallback
        )
        self.w.open()

    def editCallback(self, sender):
        print("editCallback")

Test()
```
