### ISSUE TITLE
Deactivate some RadioGroup cells

### ISSUE THREAD

**Issue by jenskutilek** [robotools/vanilla#29]
I’ve written a function for one of my scripts that allows to disable specified options in a RadioGroup. @typesupply if you are interested, I will add it to the RadioGroup class and send a pull request.

```python
from AppKit import NSCellDisabled

def setNSMatrixCellEnabled(matrix, cell_index, state):
    matrix.cells()[cell_index].setCellAttribute_to_(NSCellDisabled, not state)

matrix = self.w.the_selector.getNSMatrix()
setNSMatrixCellEnabled(matrix, 1, True)
```

**Comment by justvanrossum** [comment]
Can you see how this should be integrated into the RadioGroup class? Sounds like a useful adition.

**Comment by jenskutilek** [comment]
Oh, it’s been a while ;) This should do it: https://github.com/typesupply/vanilla/pull/49
