### ISSUE TITLE
Look at supporting Cocoa's Auto Layout.

### ISSUE THREAD

**Issue by typesupply** [robotools/vanilla#4]
In 10.7, Apple added a [really interesting](https://developer.apple.com/library/mac/documentation/userexperience/conceptual/AutolayoutPG/Articles/Introduction.html) new method for building interfaces. I think this could be a replacement for the posSize argument in the standard vanilla object constructor. It's definitely worth a try.

I have skimmed the conceptual documentation and a couple of [blog](http://inessential.com/2013/03/06/how_much_or_how_little_i_use_interface) [posts](http://oleb.net/blog/2013/03/things-you-need-to-know-about-cocoa-autolayout/) and I think the two bits of data are the layout string and an identifier hat the layout engine uses in conjunction with the layout string. These are my initial thoughts for the layout string:
1. posSize could be a triple as it has been for years or it could be a string. If it is a string, the string is the auto layout string.
2. A new autoLayout keyword argument. 

For the identifier:
1. Use the attribute name that is used when adding the object to the super view. 
2. Add a new autoLayoutIdentifier.

I think using the string as posSize and the attribute name as he identifier seem the cleanest. I'll experiment with the timing and structure of all of this.

**Comment by typemytype** [comment]
a proposal for the auto layout https://gist.github.com/typemytype/b9c85801762c579448d7

**Comment by typesupply** [comment]
> a proposal for the auto layout

From an API perspective, this looks cool. The internal code looks nice and simple, too. The only less-than-vanilla-like-thing is the constraint syntax:

`V:|-padding-[info(>=controlHeight)]-padding-[info1(>=controlHeight)]-80-|`

However, it's [well document](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/AutolayoutPG/VisualFormatLanguage.html) and we wouldn't have to reinvent the wheel so it's probably best to use it as specced by Apple.

**Comment by justvanrossum** [comment]
I'm still trying to understand that syntax, but overall this looks good!

**Comment by typesupply** [comment]
I'm going to create a branch, implement this and see what happens. I'd really like to add NSCollectionView, NSStackView and NSGridView to vanilla and those require auto layout. I'll submit a PR if it works.

**Comment by typesupply** [comment]
Regarding the PR I just submitted: there are two other views that could be useful for auto layout:

* NSGridView
* NSCollectionView

I have NSGridView wrapped and in an experiment, but it's complex and doesn't feel ready yet. I haven't wrapped NSCollectionView yet. That one may be too complex to wrap with vanilla.

I'll keep adjusting auto layout and implement things as they seem necessary. What I have now is a good starting point.

**Comment by simoncozens** [comment]
@typesupply: Did you ever get anywhere with NSGridView? I would be interested in seeing the experiment you did (and maybe finishing it).

**Comment by typesupply** [comment]
> Did you ever get anywhere with NSGridView?

No. I focused on NSCollectionView. I'll publish that at some point, but it probably won't be in vanilla. It's a pretty different set of concepts.

**Comment by simoncozens** [comment]
Fair enough; I got most of what I wanted with a list view and horrible hackery.

**Comment by typesupply** [comment]
"horrible hackery" should be the code name for vanilla. 😄
