### ISSUE TITLE
SimpleApp demo fails to launch on macOS 10.12 (Sierra)

### ISSUE THREAD

**Issue by miguelsousa** [robotools/vanilla#42]
The app compiles without errors, but on launch it fails with this error:

> Detected missing constraints for &lt;private&gt;.  It cannot be placed because there are not enough constraints to fully define the size and origin. Add the missing constraints, or set translatesAutoresizingMaskIntoConstraints=YES and constraints will be generated for you. If this view is laid out manually on macOS 10.12 and later, you may choose to not call [super layout] from your override. Set a breakpoint on DETECTED_MISSING_CONSTRAINTS to debug. This error will only be logged once.

@typemytype any clues on how to fix this? I tried to set [translatesAutoresizingMaskIntoConstraints](https://developer.apple.com/documentation/uikit/uiview/1622572-translatesautoresizingmaskintoco) somewhere in `vanilla.vanillaWindows.Window` without success.

**Comment by miguelsousa** [comment]
After adding these two lines
```python
import pdb
pdb.set_trace()
```
to **SimpleApp.py** I now get this message in Console,
> GetDYLDEntryPointWithImage(/System/Library/Frameworks/AppKit.framework/Versions/Current/AppKit,_NSCreateAppKitServicesMenu) failed.

**Comment by dyyybek** [comment]
@miguelsousa did you manage to get this working?

**Comment by miguelsousa** [comment]
https://github.com/typesupply/vanilla/pull/32 has a comment about it running on 10.12.1.

I don't know the last time I tried to compile or launch the SimpleApp.

**Comment by schriftgestalt** [comment]
What is the oldest version of macOS that should be supported by vanilla?
