### ISSUE TITLE
setShowFocusRing for vanilla controls

### ISSUE THREAD

**Issue by typemytype** [robotools/vanilla#74]
instead of divining into a pond of NS-objects a convenient method for vanilla objects switching on off the focus ring

**Comment by typesupply** [comment]
Shortcut for:

```python
obj.setFocusRingType_(NSFocusRingTypeNone)
```

Maybe it should be `setDrawFocusRing` since `vanilla.List` has a `drawFocusRing` argument.

**Comment by justvanrossum** [comment]
For the "on" state, should we be able to distinguish between `NSFocusRingTypeDefault` and `NSFocusRingTypeExterior`? I'm not quite sure what the difference is.

**Comment by typemytype** [comment]
I dont see a difference between those...

```python
import AppKit
import vanilla

w = vanilla.Window((400, 400))

w.t1 = vanilla.List((10, 10, -10, 100), [])
w.t2 = vanilla.List((10, 120, -10, 100), [])
w.t3 = vanilla.List((10, 230, -10, 100), [])


w.t1._tableView.setFocusRingType_(AppKit.NSFocusRingTypeDefault)
w.t2._tableView.setFocusRingType_(AppKit.NSFocusRingTypeNone)
w.t3._tableView.setFocusRingType_(AppKit.NSFocusRingTypeExterior)

w.open()
```

I would go for `NSFocusRingTypeDefault` and `NSFocusRingTypeNone` as True and False
