### ISSUE TITLE
Attributes to control EditText, etc. with arrow keys?

### ISSUE THREAD

**Issue by ryanbugden** [robotools/vanilla#89]
Would it be possible to add support for (Shift, Cmd) + Arrow keys within fields like `EditText` so that integers could be quickly edited? Would be great if it could be made possible to set `continuous` for arrowed but not typed input (similar to the way the inspector’s margin fields in RF behave now in 3.2)

Redirecting from the latest in conversation: https://forum.robofont.com/topic/555/metrics-auto-update-upon-value-change-in-inspector-with-arrows/8

Please let me know if I'm missing something.

**Comment by gorjious** [comment]
Any luck with this?

Trying something using List2 with number columns set as "editable": True which I am able to edit by clicking and typing to change the number but can't figure out or find a way to change the value using up / down arrow keys.

<img width="124" alt="Screenshot 2023-03-05 at 11 24 21" src="https://user-images.githubusercontent.com/23149420/222978829-e1edbf68-17eb-443e-a532-f83365bc5026.png">

**Comment by ryanbugden** [comment]
For the time being, you could try this? 
```
from lib.UI.integerEditText import NumberEditText
help(NumberEditText)
```

**Comment by typesupply** [comment]
I added this to ezui a while back where it feels more appropriate. So, I'm going to close this.
