### ISSUE TITLE
Launching vanilla from a .py script

### ISSUE THREAD

**Issue by roberto-arista** [robotools/vanilla#99]
Hi there!

I installed vanilla on a py3.7 environment and I would like to use it outside RF or Drawbot. If I try to launch the ButtonDemo script

```python
from vanilla import *

class ButtonDemo(object):

     def __init__(self):
         self.w = Window((100, 40))
         self.w.button = Button((10, 10, -10, 20), "A Button",
                            callback=self.buttonCallback)
         self.w.open()

     def buttonCallback(self, sender):
         print("button hit!")

ButtonDemo()
```

the script runs smoothly but no window appears.
Am I missing something? Do you have any advice?

Cheers

**Comment by roberto-arista** [comment]
I solved using a patched version of the SimpleApp example

```python
from __future__ import print_function
import sys
from PyObjCTools import AppHelper
import vanilla

class SimpleAppWindow(object):

    def __init__(self):
        self.w = vanilla.Window((250, 120), "Simple App Window", closable=False)
        self.w.text = vanilla.TextBox((10, 10, -10, 70), "This is a simple window. It doesn't do much. You see that button? Press it and some text will be printed in Console.app.")
        self.w.button = vanilla.Button((10, 90, -10, 20), "Press me", callback=self.buttonCallback)
        self.w.open()

    def buttonCallback(self, sender):
        print("You pressed the button!")
        sys.stdout.flush()

SimpleAppWindow()

if __name__ == "__main__":
    AppHelper.runEventLoop()

```

**Comment by justvanrossum** [comment]
There was this thing where you could run a vanilla window without an app container, but I can't find it right now.

**Comment by typemytype** [comment]
```python
import vanilla

class MyController(object):

    def __init__(self):
        self.w = vanilla.Window((400, 400))
        self.w.open()

from vanilla.test.testTools import executeVanillaTest
executeVanillaTest(MyController)
``` 

see https://github.com/robotools/vanilla/blob/master/Lib/vanilla/test/testTools.py#L12

**Comment by roberto-arista** [comment]
<3

thank you!

**Comment by mathieureguer** [comment]
Sorry to comment on a closed issue 😅

`executeVanillaTest()` works great until you have an `EditText` field in the window. 
All text input by the user is grabbed by the terminal window rather than the vanilla mini app. 

```python
import vanilla
from vanilla.test.testTools import executeVanillaTest

class TestWindow():
    def __init__(self):
        self.w = vanilla.Window((400, 500), "hello")
        self.w.button = vanilla.Button((20, 20, -20, 20), "boom")
        self.w.text = vanilla.EditText((20, 60, -20, 20))
        self.w.open()
        self.w.select()


if __name__ == "__main__":
    executeVanillaTest(TestWindow)
```

I imagine `executeVanillaTest` was never meant to be used for something like that. 
Do you think it would that's something remotely possible? I guess terminal.app would not be that happy with giving away its user inputs...

**Comment by justvanrossum** [comment]
> executeVanillaTest() works great until you have an EditText field in the window.

Hm, works fine for me on 10.15.7.

**Comment by frankrolf** [comment]
Does not work for me on 10.15.7 – all text input appears in the Terminal window.

**Comment by mathieureguer** [comment]
Oh that's interesting! Thank you for testing it out.
I am on 10.14.6, with terminal.app on zsh and all text input are registered by the terminal window, just like Frank said.

![Screenshot 2021-09-10 at 14 17 27](https://user-images.githubusercontent.com/885217/132852732-9395f9af-6eba-4162-95c7-c1ed67141e8d.png)

**Comment by typemytype** [comment]
fine on 10.13 (both in terminal as iTerm) 

strange: Just and Frank tested on the same OS but with different results. Are you both using the same latest version of vanilla? (I know vanilla does not have a decent version number)

The window gets full focus: the toolbar is not grayed out, top right buttons are not grayed out, focus rings around the EditText control?

**Comment by justvanrossum** [comment]
I am using Terminal, and have tried with both bash and zsh: same results. I am using Python 3.7, latest vanilla, latest pyobjc, in a virtual environment.

**Comment by justvanrossum** [comment]
@frankrolf and @mathieureguer, which version of Python do you use, and where is it from? (Eg. python.org, homebrew, etc.)

**Comment by mathieureguer** [comment]
@joachimvu suggested that pyenv might be the culprit.
I use python 3.7.4, installed via pyenv. I think @frankrolf does use pyenv as well.
Deactivating pyenv and switching to a python installed from python.org makes the problem disappear. 🤯
I have no idea what pyenv is doing to mess with keyboard input, whether its a feature or a bug or if that's just a faulty configuration on my part…

The good news is that `executeVanillaTest()` works perfectly fine once your outside of pyenv!

**Comment by justvanrossum** [comment]
Thanks, that's good to know.

FWIW: I strictly use python.org installers myself, and recommend that to anyone willing to listen. Homebrew, Anaconda, pyenv: I'm not getting near that stuff.

**Comment by mathieureguer** [comment]
I am starting to understand why 😋

**Comment by frankrolf** [comment]
Thanks, good to know! I use `pyenv` indeed and found it to be very useful for my purposes.
I am curious why this happens though (Mathieu you seem to know)?

**Comment by mathieureguer** [comment]
Oh sorry, I meant that I was starting to understand why Just was using only python.org installers. 
I am absolutely not starting to understand why pyenv python behaves that way. 😑

**Comment by punchcutter** [comment]
I've run into similar problems with conda and pyenv and I think some other virtual envs. It's always something with GUI. Since I discovered the problem years ago I know to just switch to a regular Python venv. Most recently it happened with wxpython where it failed in conda, but everything is perfect with built in venv.

**Comment by joachimvu** [comment]
> @joachimvu suggested that pyenv might be the culprit.
> I use python 3.7.4, installed via pyenv. I think @frankrolf does use pyenv as well.
> Deactivating pyenv and switching to a python installed from python.org makes the problem disappear. 🤯
> I have no idea what pyenv is doing to mess with keyboard input, whether its a feature or a bug or if that's just a faulty configuration on my part…
> 
> The good news is that `executeVanillaTest()` works perfectly fine once your outside of pyenv!

I ran into [this issue](https://github.com/typemytype/drawbot/issues/406) with pyenv and drawbot. I still havent figured out since what it is with pyenv python versions that cause problems. I’m really fond of pyenv’s way of managing python versions and activating environments when `cd`ing into projects, but it is unreliable, although I never had any issues outside of these two (drawbot and vanilla) type design-specific libs.

**Comment by mathieureguer** [comment]
Oh, I just noticed something. 
Without pyenv, when the `executeVanillaTest()`is launched from the terminal, clicking on the vanilla window will actually switch the top menu bar to the little autonomous python app created by the script. 
With pyenv, the window launches, but the terminal.app menu bar always stays on. You are never really in the autonomous python app. I guess that is why the terminal windows catches all key inputs.

**Comment by justvanrossum** [comment]
> With pyenv, the window launches, but the terminal.app menu bar always stays on. You are never really in the autonomous python app

Yes, that is indeed the problem. For this UI stuff to work, it needs to be run from an app bundle, and pyenv (and Conda, maybe also Brew) don't do that.
